model: HyperHawkes

use_excitation: True
use_self_excitation: True
use_base_excitation: True

warm_up_epochs: 0
hgnn_layers: 3
n_clusters: 2048

n_heads: 4
n_levels: 4
attn_dropout_prob: 0.5
emb_dropout_prob: 0.5
