model: HyperHawkes

use_atten_mixer: True
use_base_excitation: True
use_self_item_excitation: True
use_self_intent_excitation: True

hgnn_layers: 3

n_clusters: 512
cl_weight: 0.005
thresh_cluster: 0.2
temperature: 0.25
mask_ratio: 0.5

attn_dropout_prob: 0.2
emb_dropout_prob: 0.2
n_heads: 8
n_levels: 1