model: HyperHawkes

use_cl: True
use_atten_mixer: True
use_base_excitation: True
use_self_item_excitation: True
use_self_intent_excitation: True

hgnn_layers: 2 #3

n_clusters: 8
cl_weight: 0.005
thresh_cluster: 0.05 #0.1
temperature: 0.75
mask_ratio: 0.3

attn_dropout_prob: 0.2
emb_dropout_prob: 0.2
n_heads: 4
n_levels: 2