model: HyperHawkes

use_atten_mixer: True
use_base_excitation: True
use_self_item_excitation: True
use_self_intent_excitation: True

hgnn_layers: 3
n_clusters: 16

attn_dropout_prob: 0.2
emb_dropout_prob: 0.2
n_heads: 4
n_levels: 2