model: HyperHawkes

use_atten_mixer: True
use_base_excitation: True
use_self_item_excitation: True
use_self_intent_excitation: True

hgnn_layers: 3

n_clusters: 128
cl_weight: 0.05
thresh_cluster: 0.1
temperature: 0.1
mask_ratio: 0.5

attn_dropout_prob: 0.5
emb_dropout_prob: 0.5
n_heads: 4 #2
n_levels: 8 #4