model: HyperHawkes

use_atten_mixer: True
use_base_excitation: True
use_self_item_excitation: True
use_self_intent_excitation: True

hgnn_layers: 3
n_clusters: 128

attn_dropout_prob: 0.5
emb_dropout_prob: 0.5
n_heads: 4
n_levels: 4